"""
Briefing — cockpit display from living system state.

SINGLE WRITER for CLAUDE.md. All paths funnel through write_claude_md():
  - MOKSHA heartbeat (every 5s via moksha_bridge hook)
  - On-demand (synthesize_briefing tool, agent request)
  - External trigger (PR, push, federation sync)

Three layers compose the CLAUDE.md:
  1. Auto-generated orientation from living code (replaces static conventions.md)
  2. Validated agent annotations (from steward.annotations pipeline)
  3. Dynamic state from context_bridge (health, issues, senses, federation)

No manual files. No second writer. One pipeline.
"""

from __future__ import annotations

import hashlib
import logging
import time
from pathlib import Path

logger = logging.getLogger("STEWARD.BRIEFING")

# ── Write Synchronization ────────────────────────────────────────────
# Single writer with rate limiting + hash dedup to prevent filesystem churn.
_last_write: float = 0.0
_last_hash: str = ""
_MIN_WRITE_INTERVAL: float = 5.0  # seconds


def write_claude_md(cwd: str | None = None, force: bool = False) -> bool:
    """Single writer for CLAUDE.md. All triggers call this.

    Returns True if file was written, False if skipped (rate limit or unchanged).
    """
    global _last_write, _last_hash

    now = time.time()
    if not force and (now - _last_write) < _MIN_WRITE_INTERVAL:
        return False

    cwd = cwd or str(Path.cwd())
    briefing = generate_briefing(cwd)

    # Hash dedup — skip write if content unchanged
    content_hash = hashlib.sha256(briefing.encode()).hexdigest()[:16]
    if content_hash == _last_hash and not force:
        _last_write = now
        return False

    claude_md = Path(cwd) / "CLAUDE.md"
    claude_md.write_text(briefing, encoding="utf-8")
    _last_write = now
    _last_hash = content_hash
    return True


def generate_briefing(cwd: str | None = None) -> str:
    """Generate cockpit briefing from living system state."""
    cwd = cwd or str(Path.cwd())

    from steward.context_bridge import assemble_context, collect_architecture_metadata

    ctx = assemble_context(cwd)

    # Cold-start: merge cached context.json from last heartbeat
    if not ctx.get("federation", {}).get("peers") and not ctx.get("immune"):
        _merge_cached_context(ctx, cwd)

    arch = collect_architecture_metadata()
    return _format(ctx, arch, cwd)


def _merge_cached_context(ctx: dict, cwd: str) -> None:
    """Fill empty sections from last heartbeat's context.json."""
    import json

    path = Path(cwd) / ".steward" / "context.json"
    if not path.exists():
        return
    try:
        cached = json.loads(path.read_text())
        for key in ("federation", "immune", "health", "cetana"):
            if not ctx.get(key) and cached.get(key):
                ctx[key] = cached[key]
    except (json.JSONDecodeError, OSError):
        pass


def _format(ctx: dict, arch: dict, cwd: str = ".") -> str:
    """Cockpit layout: header → orientation → annotations → critical → state → action → architecture."""
    parts: list[str] = []
    name = ctx.get("project", {}).get("name", "") or Path(cwd).resolve().name

    # ── 0. GENERATION HEADER ──
    parts.append(
        "<!-- AUTO-GENERATED by steward briefing pipeline. "
        "Do not edit directly. Use the `annotate` tool to contribute knowledge. -->"
    )

    # ── 1. IDENTITY ──
    ns = arch.get("north_star", "")
    parts.append(f"# {name}")
    if ns:
        parts.append(f"**{ns}**")

    # Seed + position from MahaMantra (if available)
    seed_info = _get_seed_info()
    if seed_info:
        parts.append(seed_info)

    # ── 2. CRITICAL (only if something is actually wrong) ──
    critical = _collect_critical(ctx)
    if critical:
        parts.append("\n## Critical")
        for c in critical:
            parts.append(f"- {c}")
    else:
        parts.append("\n*No critical issues.*")

    # ── 3. ORIENTATION (auto-generated from code — replaces conventions.md) ──
    orientation = _generate_orientation(arch, cwd)
    if orientation:
        parts.append(f"\n{orientation}")

    # ── 4. AGENT KNOWLEDGE (validated annotations from pipeline) ──
    knowledge = _collect_annotations()
    if knowledge:
        parts.append("\n## Agent Knowledge")
        parts.append(knowledge)

    # ── 5. ENVIRONMENT (dynamic — what senses perceive right now) ──
    _append_environment(parts, ctx)

    # ── 6. ACTION (issues + gaps) ──
    _append_action(parts, ctx)

    # ── 7. ARCHITECTURE (dynamic — services, phases, tools from living code) ──
    _append_architecture(parts, arch)

    # ── 8. SESSIONS (compact) ──
    sessions = ctx.get("sessions", {})
    stats = sessions.get("stats", {})
    if stats and stats.get("total", 0) > 0:
        parts.append(f"\nSessions: {stats.get('total', 0)} total, success rate {stats.get('success_rate', 0):.0%}")

    return "\n".join(parts)


# ── Section Builders ──────────────────────────────────────────────────


def _get_seed_info() -> str:
    """Get MahaMantra seed + position for identity line."""
    try:
        from vibe_core.mahamantra import mahamantra

        vm = mahamantra("steward")
        seed = vm.get("seed", "")
        position = vm.get("position", "")
        compression = vm.get("compression_ratio", "")
        parts = []
        if seed:
            parts.append(f"Seed `{seed}`")
        if position:
            parts.append(f"position {position}")
        if compression:
            parts.append(f"{compression}x compression")
        return " · ".join(parts) if parts else ""
    except Exception:
        return ""


def _generate_orientation(arch: dict, cwd: str) -> str:
    """Auto-generate orientation from living code.

    Replaces the static conventions.md with content derived from:
      - Architecture metadata (services, tools, phases)
      - Makefile / pyproject.toml (workflow)
      - Code structure (key directories from filesystem)
    """
    parts: list[str] = ["## Status"]

    # ── Key directories (from filesystem) ──
    key_dirs = _detect_key_directories(cwd)
    if key_dirs:
        parts.append("")
        for d in key_dirs:
            parts.append(f"- `{d['path']}/` — {d['desc']}")

    # ── Invariants (from code constants + architecture) ──
    invariants = _extract_invariants(arch)
    if invariants:
        parts.append("\n### Invariants")
        for inv in invariants:
            parts.append(f"- {inv}")

    # ── Development workflow (from Makefile + pyproject.toml) ──
    workflow = _extract_workflow(cwd)
    if workflow:
        parts.append("\n### Workflow")
        for step in workflow:
            parts.append(f"- {step}")

    return "\n".join(parts)


def _detect_key_directories(cwd: str) -> list[dict]:
    """Detect key directories from filesystem."""
    root = Path(cwd)
    dirs = []

    known = {
        "steward/antahkarana": "cognitive pipeline: manas, buddhi, chitta, gandha, vedana",
        "steward/senses": "environmental perception (git, project, code, testing, health)",
        "steward/tools": "tool implementations",
        "steward/hooks": "MURALI phase hooks",
        "steward/loop": "agent loop engine",
        "steward/provider": "LLM provider chamber",
        "steward/interfaces": "external interfaces (telegram, API, agent-internet)",
        "steward/healer": "compound fixer pipeline",
        "data/federation": "nadi protocol (peer.json, inbox, outbox)",
        "tests": "test suite",
    }

    for rel_path, desc in known.items():
        if (root / rel_path).is_dir():
            dirs.append({"path": rel_path, "desc": desc})

    return dirs


def _extract_invariants(arch: dict) -> list[str]:
    """Extract invariants from architecture metadata."""
    invariants = []

    # North Star immutability
    ns = arch.get("north_star")
    if ns:
        invariants.append(
            "`NORTH_STAR_TEXT` in services.py is a MahaCompression seed — modifying it breaks all alignment hashes"
        )

    # Tool protocol
    invariants.append(
        "Tools must inherit `vibe_core.tools.tool_protocol.Tool` "
        "and implement name/description/parameters_schema/validate/execute"
    )

    # Safety gates
    invariants.append("Safety gates: Narasimha (bash threat analysis), Iron Dome (write protection), CBR (token quota)")

    # Identity
    invariants.append("Identity comes from `data/federation/peer.json` — never hardcode owner/org strings")

    # Exception handling
    invariants.append("`except: pass` is Anti-Buddhi — always log or propagate")

    return invariants


def _extract_workflow(cwd: str) -> list[str]:
    """Extract development workflow from Makefile and pyproject.toml."""
    root = Path(cwd)
    workflow = []

    # Check Makefile
    makefile = root / "Makefile"
    if makefile.is_file():
        try:
            content = makefile.read_text(encoding="utf-8")
            if "check:" in content:
                workflow.append("`make check` runs everything: lint → security → tests")
        except OSError:
            pass

    # Check pyproject.toml for ruff + pytest config
    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        try:
            content = pyproject.read_text(encoding="utf-8")
            if "ruff" in content:
                workflow.append("`ruff check && ruff format` before every commit")
            if "pytest" in content:
                workflow.append("`python -m pytest tests/ -q --timeout=30`")
            if "bandit" in content:
                workflow.append("`bandit -r steward/ -ll -q` for security")
            # Extract Python version requirement
            if "python_requires" in content:
                for line in content.splitlines():
                    if "python_requires" in line and ">=" in line:
                        ver = line.split(">=")[1].strip().strip('"').strip("'")
                        workflow.append(f"Python {ver}")
                        break
        except OSError:
            pass

    return workflow


def _collect_annotations() -> str:
    """Collect validated annotations from the knowledge pipeline."""
    try:
        from steward.annotations import format_for_briefing

        return format_for_briefing()
    except Exception:
        return ""


def _collect_critical(ctx: dict) -> list[str]:
    """Collect critical alerts from system state."""
    critical: list[str] = []

    health = ctx.get("health", {})
    h_val = health.get("value", 1.0)
    if isinstance(h_val, (int, float)) and h_val < 0.5:
        critical.append(f"Health CRITICAL: {h_val} ({health.get('guna', '?')})")

    immune = ctx.get("immune", {})
    if immune.get("breaker", {}).get("tripped"):
        critical.append("Immune breaker TRIPPED — healing suspended")
    if immune.get("heals_rolled_back", 0) > 0:
        critical.append(f"{immune['heals_rolled_back']} heals rolled back")

    fed = ctx.get("federation", {})
    dead = fed.get("dead", 0) if isinstance(fed.get("dead"), int) else len(fed.get("dead_ids", []))
    if dead:
        critical.append(f"{dead} DEAD peers in federation")

    senses = ctx.get("senses", {})
    pain = senses.get("total_pain", 0)
    if isinstance(pain, (int, float)) and pain > 0.7:
        critical.append(f"High pain: {pain:.2f}")

    return critical


def _append_environment(parts: list[str], ctx: dict) -> None:
    """Append environment perception — senses, health, immune, federation."""
    senses = ctx.get("senses", {})
    prompt = senses.get("prompt_summary", "")

    # Senses produce their own "## Environment Perception" header
    if prompt:
        parts.append(f"\n{prompt.strip()}")
    else:
        parts.append("\n## Environment")

    health = ctx.get("health", {})
    if health:
        parts.append(f"Health: {health.get('value', '?')} ({health.get('guna', '?')})")

    immune = ctx.get("immune", {})
    if immune:
        parts.append(
            f"Immune: {immune.get('heals_attempted', 0)} attempts, "
            f"{immune.get('heals_succeeded', 0)} succeeded, "
            f"breaker {'TRIPPED' if immune.get('breaker', {}).get('tripped') else 'OK'}"
        )

    fed = ctx.get("federation", {})
    peers = fed.get("peers", [])
    if peers:
        parts.append(f"\nFederation: {len(peers)} peers")
        parts.append("| Peer | Status | Trust |")
        parts.append("|------|--------|-------|")
        for p in peers:
            parts.append(f"| {p.get('agent_id', '?')} | {p.get('status', '?')} | {p.get('trust', '?')} |")


def _append_action(parts: list[str], ctx: dict) -> None:
    """Append action items — issues and gaps."""
    issues = ctx.get("issues", [])
    gaps = ctx.get("gaps", {})
    active_gaps = gaps.get("active", [])

    if not issues and not active_gaps:
        return

    parts.append("\n## Action")

    if issues:
        for i in issues:
            num = i.get("number", "?")
            title = i.get("title", "?")
            labels = i.get("labels", [])
            label_str = ""
            if labels:
                label_str = " " + " ".join(f"[{lb}]" for lb in labels[:3])
            parts.append(f"- #{num}: {title}{label_str}")

    if active_gaps:
        parts.append("")
        parts.append("Gaps:")
        for g in active_gaps[:5]:
            parts.append(f"- [{g.get('category', '?')}] {g.get('description', '?')}")


def _append_architecture(parts: list[str], arch: dict) -> None:
    """Append architecture — services with docstrings, phases, tools."""
    parts.append("\n## Architecture")

    services = arch.get("services", {})
    if services:
        parts.append(f"{len(services)} services · {len(arch.get('kshetra', []))} tattvas")

        # Compact: just list service names, not all docstrings
        svc_names = sorted(services.keys())
        if len(svc_names) > 15:
            shown = svc_names[:15]
            parts.append(f"Services: {', '.join(f'`{s}`' for s in shown)} +{len(svc_names) - 15} more")
        else:
            parts.append(f"Services: {', '.join(f'`{s}`' for s in svc_names)}")

    phases = arch.get("phases", {})
    hooks = arch.get("hooks", {})
    if phases:
        phase_parts = []
        for p, desc in phases.items():
            hook_info = hooks.get(p, {})
            if isinstance(hook_info, dict):
                count = hook_info.get("count", 0)
            else:
                count = len(hook_info) if isinstance(hook_info, list) else 0
            phase_parts.append(f"**{p}**({count})")
        parts.append(f"MURALI: {' → '.join(phase_parts)}")
